### ISSUE TITLE
Odd elements available to "toggle visibility" in Multi wrapper

### ISSUE THREAD

**Issue by stemilymill** [phetsims/molecule-polarity#122] opened 2021-07-30 17:01 UTC
Found while testing for https://github.com/phetsims/qa/issues/680

While testing the [Multi wrapper](https://phet-dev.colorado.edu/html/molecule-polarity/1.2.0-dev.3/phet-io/wrappers/multi/), the elements available to toggle visibility seemed very strange - essentially overlaying two screens.

I don't really know how to document/describe this, so apologies for that.

**Home Screen visible, layered behind Two Atoms screen and Three Atoms screen**
![extra things showing up multi wrapper 1](https://user-images.githubusercontent.com/85511101/127685980-e377c52b-e60d-4c28-b97c-fd48ed25a674.jpg)

**Two Atoms screen layered behind Three Atoms screen**
![extra things showing up multi wrapper 2](https://user-images.githubusercontent.com/85511101/127685995-e42b5faa-ce72-4534-9f24-0d10d7b1db27.jpg)

**Comment by pixelzoom** [comment] 2021-07-30 17:14
> I don't really know how to document/describe this, so apologies for that.

@Nancy-Salpepi I'm not at all familiar with the Multi wrapper. So that makes 2 of us :)

I'll need steps to reproduce, and more information -- maybe from @zepumph or @samreid?   Each time that I load the Multi wrapper, I see different tandems next to "Toggle visibility:".  Is this only a problem with `homeScreen.view.visibleProperty`?  Is this a sim-specific or general problem? I can't imagine why a home screen icon is showing up on the Two Atoms screen.

**Comment by Nancy-Salpepi** [comment] 2021-07-30 17:28
Hi. It was Emily  @stemilymill that found this issue not me.

**Comment by pixelzoom** [comment] 2021-07-30 17:34
Oops, sorry @Nancy-Salpepi!  Reassigning to @stemilymill.

**Comment by zepumph** [comment] 2021-07-30 17:45
Responding to your questions. . .

>Each time that I load the Multi wrapper, I see different tandems next to "Toggle visibility:". What's going on here?

The multi wrapper chooses a random `visibilityProperty` on each load, and wires up a checkbox to toggle it. This wrapper is meant to serve as a template about how you could embed multiple versions of the same sim into the same webpage. This customization is meant to demonstrate how you are not toggling this in both sims, but just the single instance.

>Is this only a problem with homeScreen.view.visibleProperty? I can't imagine why a home screen icon is showing up on the Two Atoms screen.

Since it chooses it at random, it looks like it can grab the same visibleProperty that the Sim toggles when changing screens. I'll make sure to prevent that top level Node from being controlled.

>Is this a sim-specific or general problem?

General.

I'll commit and cherry pick the fix to the molecule polarity branch.

**Comment by zepumph** [comment] 2021-07-30 17:47
Oh, right, it's a dev version.

**Comment by zepumph** [comment] 2021-07-30 17:48
@stemilymill can you please try to reproduce on master with a link like https://bayes.colorado.edu/dev/phettest/phet-io-wrappers/multi/?sim=molecule-polarity&phetioDebug. Note this would be general to all sims, not just molecule-polarity.

**Comment by stemilymill** [comment] 2021-07-31 01:17
Unable to reproduce with above link.

**Closed** 2021-07-31 03:17 UTC
Labels: dev:phet-io, status:ready-for-review, type:bug
