### ISSUE TITLE
Text may shift while rotating molecule on Chromebook

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-polarity#164] opened 2023-06-20 20:12 UTC
**Test device**
Chromebook  (Lenovo 100e)

**Operating System**
ChromeOS 114

**Browser**
chrome 

**Problem description**
For https://github.com/phetsims/qa/issues/956, on the Three Atoms Screen, when rotating molecules with large dipole moments the text in the electronegativity panels moves. I have only seen this with the Chromebook so far. 

**Steps to reproduce**
1. On the Three Atoms screen, in the Electronegativity panel for Atom B, move the slider all the way to the right.
2. Move Atom C closer to Atom A.
3. Rotate Molecule Around

**Visuals**

https://github.com/phetsims/molecule-polarity/assets/87318828/84478963-de15-4ac4-8b05-e3c7dc720111

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Molecule Polarity‬
URL: https://phet-dev.colorado.edu/html/molecule-polarity/1.3.0-rc.1/phet/molecule-polarity_all_phet.html
Version: 1.3.0-rc.1 2023-06-15 19:01:21 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language: en-US
Window: 1583x773
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by arouinfar** [comment] 2023-06-20 22:39
Good observation @Nancy-Salpepi. Does it also happen in the published version of the sim?

This looks like it could be a case of https://github.com/phetsims/scenery/issues/1289.

**Comment by pixelzoom** [comment] 2023-06-20 23:20
Molecule Polarity is not currently applying the `preventFit: true` workaround to its ScreenViews. So this is almost certainly due to https://github.com/phetsims/scenery/issues/1289.  

Options:
(1) Fix https://github.com/phetsims/scenery/issues/1289
(2) Apply the `preventFit: true` workaround for the Nth time.
(3) Do nothing.

I'm inclined to do (3) so that we don't keep avoiding (1).  But I have the feeling we'll end up doing (2). 

@arouinfar @kathy-phet thoughts?

**Comment by kathy-phet** [comment] 2023-06-21 06:05
I would vote for (2) and move on.

**Comment by pixelzoom** [comment] 2023-06-21 14:39
https://github.com/phetsims/scenery/issues/1289 usually happens on Chrome, but that's not the case here. I can't reproduce it on Chrome, Safari, or Firefox on macOS 13.4.  I can't reproduce it on iPadOS 16.5.   So I can't even verify that the `preventFit: true` workaround is appropriate without iterating with QA.  That will not happen before my vacation, so will defer the next RC until at least July 5. 

This is a very minor graphics artifact that does not affect usability of the sim, and it only happens in specific cases. And it does not seem like it's worth the cost to address during RC.  So unless this problem is present on Windows, my recommendation is (3) --- "do nothing".   But if @arouinfar and @kathy-phet really want to do (2), I'll proceed.

**Comment by pixelzoom** [comment] 2023-06-21 16:59
@arouinfar and I discussed.   Adding `preventFit: true` is not just a matter of just adding a line of code and moving on.  Using `preventFit: true` can have negative performance implications, and requires re-testing on all platforms.  And that fact that I can't reproduce it in this case makes it harder to verify, and more time-consuming to fix.  So we agreed that if it's only a problem on Chromebook, then it's not worth the cost and delay for this sim, and we will do nothing.

@Nancy-Salpepi have you seen this problem on Windows and its supported browsers?

**Comment by Nancy-Salpepi** [comment] 2023-06-21 19:22
I can't reproduce it in Windows or on the Mac.

**Comment by pixelzoom** [comment] 2023-06-21 21:19
Thanks @Nancy-Salpepi.

Closing as "won't fix".

**Closed by pixelzoom** 2023-06-21 21:19 UTC
Labels: type:bug
